2022-03-19 00:25:30 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:25:30 [INFO] : 正在获取 [数字观星POC++] 威胁情报...
2022-03-19 00:25:32 [INFO] : 得到 [数字观星POC++] 最新威胁情报 [0] 条
2022-03-19 00:25:32 [INFO] : --------------------------------------------
2022-03-19 00:25:32 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:25:32 [INFO] : 正在获取 [阿里云] 威胁情报...
2022-03-19 00:25:33 [INFO] : 得到 [阿里云] 最新威胁情报 [0] 条
2022-03-19 00:25:33 [INFO] : --------------------------------------------
2022-03-19 00:25:33 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:25:33 [INFO] : 正在获取 [国家信息安全漏洞共享平台（CNVD）] 威胁情报...
2022-03-19 00:25:54 [INFO] : 得到 [国家信息安全漏洞共享平台（CNVD）] 最新威胁情报 [1] 条
2022-03-19 00:25:54 [INFO] : --------------------------------------------
2022-03-19 00:25:54 [INFO] : 
==============================================
[ TITLE ] Arista VEOS存在拒绝服务漏洞
[ TIME  ] 2022-03-19 00:25:34
[ CVE   ] CNVD-2022-16682
[ SRC   ] 国家信息安全漏洞共享平台（CNVD）
[ URL   ] https://www.cnvd.org.cn/flaw/show/CNVD-2022-16682
2022-03-19 00:25:54 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:25:54 [INFO] : 正在获取 [国家信息安全漏洞库（CNNVD）] 威胁情报...
2022-03-19 00:26:08 [INFO] : 得到 [国家信息安全漏洞库（CNNVD）] 最新威胁情报 [0] 条
2022-03-19 00:26:08 [INFO] : --------------------------------------------
2022-03-19 00:26:08 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:26:08 [INFO] : 正在获取 [360 网络安全响应中心] 威胁情报...
2022-03-19 00:26:10 [INFO] : 得到 [360 网络安全响应中心] 最新威胁情报 [0] 条
2022-03-19 00:26:10 [INFO] : --------------------------------------------
2022-03-19 00:26:10 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:26:10 [INFO] : 正在获取 [美国国家漏洞数据库（NVD）] 威胁情报...
2022-03-19 00:26:11 [INFO] : 得到 [美国国家漏洞数据库（NVD）] 最新威胁情报 [4] 条
2022-03-19 00:26:11 [INFO] : --------------------------------------------
2022-03-19 00:26:11 [INFO] : 
==============================================
[ TITLE ] SPIP before 3.2.14 and 4.x before 4.0.5 allows remote authenticated editors to execute arbitrary code.
[ TIME  ] 2022-03-10 17:48:01 
[ CVE   ] CVE-2022-26846
[ SRC   ] 美国国家漏洞数据库（NVD）
[ URL   ] https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2022-26846
2022-03-19 00:26:11 [INFO] : 
==============================================
[ TITLE ] Veritas System Recovery (VSR) 18 and 21 stores a network destination password in the Windows registry during configuration of the backup configuration. This could allow a Windows user (who has sufficient privileges) to access a network file system that they were not authorized to access.
[ TIME  ] 2022-03-10 17:47:58 
[ CVE   ] CVE-2022-26778
[ SRC   ] 美国国家漏洞数据库（NVD）
[ URL   ] https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2022-26778
2022-03-19 00:26:11 [INFO] : 
==============================================
[ TITLE ] An XML Entity Expansion (XEE) issue was discovered in Tryton Application Platform (Server) 5.x through 5.0.45, 6.x through 6.0.15, and 6.1.x and 6.2.x through 6.2.5, and Tryton Application Platform (Command Line Client (proteus)) 5.x through 5.0.11, 6.x through 6.0.4, and 6.1.x and 6.2.x through 6.2.1. An unauthenticated user can send a crafted XML-RPC message to consume all the resources of the server.
[ TIME  ] 2022-03-10 17:47:52 
[ CVE   ] CVE-2022-26662
[ SRC   ] 美国国家漏洞数据库（NVD）
[ URL   ] https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2022-26662
2022-03-19 00:26:11 [INFO] : 
==============================================
[ TITLE ] An XXE issue was discovered in Tryton Application Platform (Server) 5.x through 5.0.45, 6.x through 6.0.15, and 6.1.x and 6.2.x through 6.2.5, and Tryton Application Platform (Command Line Client (proteus)) 5.x through 5.0.11, 6.x through 6.0.4, and 6.1.x and 6.2.x through 6.2.1. An authenticated user can make the server parse a crafted XML SEPA file to access arbitrary files on the system.
[ TIME  ] 2022-03-10 17:47:52 
[ CVE   ] CVE-2022-26661
[ SRC   ] 美国国家漏洞数据库（NVD）
[ URL   ] https://web.nvd.nist.gov/view/vuln/detail?vulnId=CVE-2022-26661
2022-03-19 00:26:11 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:26:11 [INFO] : 正在获取 [信息安全漏洞门户] 威胁情报...
2022-03-19 00:26:11 [INFO] : 得到 [信息安全漏洞门户] 最新威胁情报 [0] 条
2022-03-19 00:26:11 [INFO] : --------------------------------------------
2022-03-19 00:26:11 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:26:11 [INFO] : 正在获取 [绿盟] 威胁情报...
2022-03-19 00:26:12 [INFO] : 得到 [绿盟] 最新威胁情报 [0] 条
2022-03-19 00:26:12 [INFO] : --------------------------------------------
2022-03-19 00:26:12 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:26:12 [INFO] : 正在获取 [奇安信] 威胁情报...
2022-03-19 00:26:12 [INFO] : 得到 [奇安信] 最新威胁情报 [0] 条
2022-03-19 00:26:12 [INFO] : --------------------------------------------
2022-03-19 00:26:12 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:26:12 [INFO] : 正在获取 [红后] 威胁情报...
2022-03-19 00:26:13 [INFO] : 得到 [红后] 最新威胁情报 [0] 条
2022-03-19 00:26:13 [INFO] : --------------------------------------------
2022-03-19 00:26:13 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:26:13 [INFO] : 正在获取 [斗象] 威胁情报...
2022-03-19 00:26:15 [INFO] : 得到 [斗象] 最新威胁情报 [0] 条
2022-03-19 00:26:15 [INFO] : --------------------------------------------
2022-03-19 00:26:15 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:26:15 [INFO] : 正在获取 [Tenable (Nessus)] 威胁情报...
2022-03-19 00:26:16 [INFO] : 得到 [Tenable (Nessus)] 最新威胁情报 [2] 条
2022-03-19 00:26:16 [INFO] : --------------------------------------------
2022-03-19 00:26:16 [INFO] : 
==============================================
[ TITLE ] Automotive Grade Linux Kooky Koi 11.0.0, 11.0.1, 11.0.2, 11.0.3, 11.0.4, and 11.0.5 is affected by Incorrect Access Control in usr/bin/afb-daemon. To exploit the vulnerability, an attacker should send a well-crafted HTTP (or WebSocket) request to the socket listened by the afb-daemon process. No credentials nor user interactions are required.
[ TIME  ] 2022-03-18 12:15:00
[ CVE   ] CVE-2022-24595
[ SRC   ] Tenable (Nessus)
[ URL   ] https://www.tenable.com/cve/CVE-2022-24595
2022-03-19 00:26:16 [INFO] : 
==============================================
[ TITLE ] Memory leak in icmp6 implementation in Linux Kernel 5.13+ allows a remote attacker to DoS a host by making it go out-of-memory via icmp6 packets of type 130 or 131. We recommend upgrading past commit 2d3916f3189172d5c69d33065c3c21119fe539fc.
[ TIME  ] 2022-03-18 12:15:00
[ CVE   ] CVE-2022-0742
[ SRC   ] Tenable (Nessus)
[ URL   ] https://www.tenable.com/cve/CVE-2022-0742
2022-03-19 00:26:16 [INFO] : [邮件] 正在推送威胁情报...
2022-03-19 00:26:16 [INFO] : [邮件] 收件人清单： ['207176126@qq.com']
2022-03-19 00:26:17 [INFO] : [邮件] 推送威胁情报成功
2022-03-19 00:26:17 [INFO] : 正在提交变更...
2022-03-19 00:26:20 [ERROR] : 提交变更失败
Traceback (most recent call last):
  File "/root/project/threat-broadcast-1/src/utils/_git.py", line 26, in auto_commit
    repo.git.push()
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git push
  stderr: 'To git@github.com:hkmayfly/threat-broadcast-1.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@github.com:hkmayfly/threat-broadcast-1.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first merge the remote changes (e.g.,
hint: 'git pull') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.'
2022-03-19 00:26:20 [ERROR] : Traceback (most recent call last):
  File "/root/project/threat-broadcast-1/src/utils/_git.py", line 26, in auto_commit
    repo.git.push()
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git push
  stderr: 'To git@github.com:hkmayfly/threat-broadcast-1.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@github.com:hkmayfly/threat-broadcast-1.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first merge the remote changes (e.g.,
hint: 'git pull') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.'
Traceback (most recent call last):
  File "/root/project/threat-broadcast-1/src/utils/_git.py", line 26, in auto_commit
    repo.git.push()
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git push
  stderr: 'To git@github.com:hkmayfly/threat-broadcast-1.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@github.com:hkmayfly/threat-broadcast-1.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first merge the remote changes (e.g.,
hint: 'git pull') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.'
<<<<<<< HEAD
2022-03-19 00:30:46 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:30:46 [INFO] : 正在获取 [数字观星POC++] 威胁情报...
2022-03-19 00:30:47 [INFO] : 得到 [数字观星POC++] 最新威胁情报 [0] 条
2022-03-19 00:30:47 [INFO] : --------------------------------------------
2022-03-19 00:30:47 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:30:47 [INFO] : 正在获取 [阿里云] 威胁情报...
2022-03-19 00:30:47 [INFO] : 得到 [阿里云] 最新威胁情报 [0] 条
2022-03-19 00:30:47 [INFO] : --------------------------------------------
2022-03-19 00:30:47 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:30:47 [INFO] : 正在获取 [国家信息安全漏洞共享平台（CNVD）] 威胁情报...
=======
2022-03-18 22:51:35 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:51:35 [INFO] : 正在获取 [数字观星POC++] 威胁情报...
2022-03-18 22:51:35 [INFO] : 得到 [数字观星POC++] 最新威胁情报 [0] 条
2022-03-18 22:51:35 [INFO] : --------------------------------------------
2022-03-18 22:51:35 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:51:35 [INFO] : 正在获取 [阿里云] 威胁情报...
2022-03-18 22:51:36 [INFO] : 得到 [阿里云] 最新威胁情报 [0] 条
2022-03-18 22:51:36 [INFO] : --------------------------------------------
2022-03-18 22:51:36 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:51:36 [INFO] : 正在获取 [国家信息安全漏洞共享平台（CNVD）] 威胁情报...
2022-03-18 22:51:57 [INFO] : 得到 [国家信息安全漏洞共享平台（CNVD）] 最新威胁情报 [0] 条
2022-03-18 22:51:57 [INFO] : --------------------------------------------
2022-03-18 22:51:57 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:51:57 [INFO] : 正在获取 [国家信息安全漏洞库（CNNVD）] 威胁情报...
2022-03-18 22:52:16 [INFO] : 得到 [国家信息安全漏洞库（CNNVD）] 最新威胁情报 [0] 条
2022-03-18 22:52:16 [INFO] : --------------------------------------------
2022-03-18 22:52:16 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:52:16 [INFO] : 正在获取 [360 网络安全响应中心] 威胁情报...
2022-03-18 22:52:16 [INFO] : 得到 [360 网络安全响应中心] 最新威胁情报 [0] 条
2022-03-18 22:52:16 [INFO] : --------------------------------------------
2022-03-18 22:52:16 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:52:16 [INFO] : 正在获取 [美国国家漏洞数据库（NVD）] 威胁情报...
2022-03-18 22:52:18 [INFO] : 得到 [美国国家漏洞数据库（NVD）] 最新威胁情报 [0] 条
2022-03-18 22:52:18 [INFO] : --------------------------------------------
2022-03-18 22:52:18 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:52:18 [INFO] : 正在获取 [信息安全漏洞门户] 威胁情报...
2022-03-18 22:52:20 [INFO] : 得到 [信息安全漏洞门户] 最新威胁情报 [0] 条
2022-03-18 22:52:20 [INFO] : --------------------------------------------
2022-03-18 22:52:20 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:52:20 [INFO] : 正在获取 [绿盟] 威胁情报...
2022-03-18 22:52:24 [INFO] : 得到 [绿盟] 最新威胁情报 [0] 条
2022-03-18 22:52:24 [INFO] : --------------------------------------------
2022-03-18 22:52:24 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:52:24 [INFO] : 正在获取 [奇安信] 威胁情报...
2022-03-18 22:52:24 [INFO] : 得到 [奇安信] 最新威胁情报 [0] 条
2022-03-18 22:52:24 [INFO] : --------------------------------------------
2022-03-18 22:52:24 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:52:24 [INFO] : 正在获取 [红后] 威胁情报...
2022-03-18 22:52:24 [INFO] : 得到 [红后] 最新威胁情报 [0] 条
2022-03-18 22:52:24 [INFO] : --------------------------------------------
2022-03-18 22:52:24 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:52:24 [INFO] : 正在获取 [斗象] 威胁情报...
2022-03-18 22:52:27 [INFO] : 得到 [斗象] 最新威胁情报 [0] 条
2022-03-18 22:52:27 [INFO] : --------------------------------------------
2022-03-18 22:52:27 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:52:27 [INFO] : 正在获取 [Tenable (Nessus)] 威胁情报...
2022-03-18 22:52:28 [INFO] : 得到 [Tenable (Nessus)] 最新威胁情报 [0] 条
2022-03-18 22:52:28 [INFO] : --------------------------------------------
2022-03-18 22:52:28 [INFO] : ('1024593536@qq.com', '${MAIL_PASS}')
2022-03-18 22:52:28 [INFO] : [邮件] 正在推送威胁情报...
2022-03-18 22:52:28 [INFO] : [邮件] 收件人清单： ['207176126@qq.com', '3074924881@qq.com']
2022-03-18 22:52:28 [ERROR] : [邮件] 推送威胁情报失败
Traceback (most recent call last):
  File "/root/project/threat-broadcast-1/src/notice/mail.py", line 47, in to_mail
    smtpObj.login(sender, password)
  File "/usr/local/python3/lib/python3.8/smtplib.py", line 734, in login
    raise last_exception
  File "/usr/local/python3/lib/python3.8/smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "/usr/local/python3/lib/python3.8/smtplib.py", line 646, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'Login Fail. Please enter your authorization code to login. More information in http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')
2022-03-18 22:52:28 [ERROR] : Traceback (most recent call last):
  File "/root/project/threat-broadcast-1/src/notice/mail.py", line 47, in to_mail
    smtpObj.login(sender, password)
  File "/usr/local/python3/lib/python3.8/smtplib.py", line 734, in login
    raise last_exception
  File "/usr/local/python3/lib/python3.8/smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "/usr/local/python3/lib/python3.8/smtplib.py", line 646, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'Login Fail. Please enter your authorization code to login. More information in http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')
Traceback (most recent call last):
  File "/root/project/threat-broadcast-1/src/notice/mail.py", line 47, in to_mail
    smtpObj.login(sender, password)
  File "/usr/local/python3/lib/python3.8/smtplib.py", line 734, in login
    raise last_exception
  File "/usr/local/python3/lib/python3.8/smtplib.py", line 723, in login
    (code, resp) = self.auth(
  File "/usr/local/python3/lib/python3.8/smtplib.py", line 646, in auth
    raise SMTPAuthenticationError(code, resp)
smtplib.SMTPAuthenticationError: (535, b'Login Fail. Please enter your authorization code to login. More information in http://service.mail.qq.com/cgi-bin/help?subtype=1&&id=28&&no=1001256')
2022-03-18 22:54:01 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:54:01 [INFO] : 正在获取 [数字观星POC++] 威胁情报...
2022-03-18 22:54:01 [INFO] : 得到 [数字观星POC++] 最新威胁情报 [0] 条
2022-03-18 22:54:01 [INFO] : --------------------------------------------
2022-03-18 22:54:01 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:54:01 [INFO] : 正在获取 [阿里云] 威胁情报...
2022-03-18 22:54:02 [INFO] : 得到 [阿里云] 最新威胁情报 [0] 条
2022-03-18 22:54:02 [INFO] : --------------------------------------------
2022-03-18 22:54:02 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:54:02 [INFO] : 正在获取 [国家信息安全漏洞共享平台（CNVD）] 威胁情报...
2022-03-18 22:54:23 [INFO] : 得到 [国家信息安全漏洞共享平台（CNVD）] 最新威胁情报 [0] 条
2022-03-18 22:54:23 [INFO] : --------------------------------------------
2022-03-18 22:54:23 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:54:23 [INFO] : 正在获取 [国家信息安全漏洞库（CNNVD）] 威胁情报...
2022-03-18 22:54:38 [INFO] : 得到 [国家信息安全漏洞库（CNNVD）] 最新威胁情报 [0] 条
2022-03-18 22:54:38 [INFO] : --------------------------------------------
2022-03-18 22:54:38 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:54:38 [INFO] : 正在获取 [360 网络安全响应中心] 威胁情报...
2022-03-18 22:54:40 [INFO] : 得到 [360 网络安全响应中心] 最新威胁情报 [0] 条
2022-03-18 22:54:40 [INFO] : --------------------------------------------
2022-03-18 22:54:40 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:54:40 [INFO] : 正在获取 [美国国家漏洞数据库（NVD）] 威胁情报...
2022-03-18 22:54:43 [INFO] : 得到 [美国国家漏洞数据库（NVD）] 最新威胁情报 [0] 条
2022-03-18 22:54:43 [INFO] : --------------------------------------------
2022-03-18 22:54:43 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:54:43 [INFO] : 正在获取 [信息安全漏洞门户] 威胁情报...
2022-03-18 22:54:45 [INFO] : 得到 [信息安全漏洞门户] 最新威胁情报 [0] 条
2022-03-18 22:54:45 [INFO] : --------------------------------------------
2022-03-18 22:54:45 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:54:45 [INFO] : 正在获取 [绿盟] 威胁情报...
2022-03-18 22:54:46 [INFO] : 得到 [绿盟] 最新威胁情报 [0] 条
2022-03-18 22:54:46 [INFO] : --------------------------------------------
2022-03-18 22:54:46 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:54:46 [INFO] : 正在获取 [奇安信] 威胁情报...
2022-03-18 22:54:47 [INFO] : 得到 [奇安信] 最新威胁情报 [0] 条
2022-03-18 22:54:47 [INFO] : --------------------------------------------
2022-03-18 22:54:47 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:54:47 [INFO] : 正在获取 [红后] 威胁情报...
2022-03-18 22:54:47 [INFO] : 得到 [红后] 最新威胁情报 [0] 条
2022-03-18 22:54:47 [INFO] : --------------------------------------------
2022-03-18 22:54:47 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:54:47 [INFO] : 正在获取 [斗象] 威胁情报...
2022-03-18 22:54:51 [INFO] : 得到 [斗象] 最新威胁情报 [0] 条
2022-03-18 22:54:51 [INFO] : --------------------------------------------
2022-03-18 22:54:51 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:54:51 [INFO] : 正在获取 [Tenable (Nessus)] 威胁情报...
2022-03-18 22:54:52 [INFO] : 得到 [Tenable (Nessus)] 最新威胁情报 [0] 条
2022-03-18 22:54:52 [INFO] : --------------------------------------------
2022-03-18 22:54:52 [INFO] : ('1024593536@qq.com', 'ntcrbdovjjdbbfde')
2022-03-18 22:54:52 [INFO] : [邮件] 正在推送威胁情报...
2022-03-18 22:54:52 [INFO] : [邮件] 收件人清单： ['3074924881@qq.com', '207176126@qq.com']
2022-03-18 22:54:53 [INFO] : [邮件] 推送威胁情报成功
2022-03-18 22:56:58 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:56:58 [INFO] : 正在获取 [数字观星POC++] 威胁情报...
2022-03-18 22:56:59 [INFO] : 得到 [数字观星POC++] 最新威胁情报 [0] 条
2022-03-18 22:56:59 [INFO] : --------------------------------------------
2022-03-18 22:56:59 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:56:59 [INFO] : 正在获取 [阿里云] 威胁情报...
2022-03-18 22:57:00 [INFO] : 得到 [阿里云] 最新威胁情报 [0] 条
2022-03-18 22:57:00 [INFO] : --------------------------------------------
2022-03-18 22:57:00 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:57:00 [INFO] : 正在获取 [国家信息安全漏洞共享平台（CNVD）] 威胁情报...
2022-03-18 22:57:22 [INFO] : 得到 [国家信息安全漏洞共享平台（CNVD）] 最新威胁情报 [0] 条
2022-03-18 22:57:22 [INFO] : --------------------------------------------
2022-03-18 22:57:22 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:57:22 [INFO] : 正在获取 [国家信息安全漏洞库（CNNVD）] 威胁情报...
2022-03-18 22:57:41 [INFO] : 得到 [国家信息安全漏洞库（CNNVD）] 最新威胁情报 [0] 条
2022-03-18 22:57:41 [INFO] : --------------------------------------------
2022-03-18 22:57:41 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:57:41 [INFO] : 正在获取 [360 网络安全响应中心] 威胁情报...
2022-03-18 22:57:41 [INFO] : 得到 [360 网络安全响应中心] 最新威胁情报 [0] 条
2022-03-18 22:57:41 [INFO] : --------------------------------------------
2022-03-18 22:57:41 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:57:41 [INFO] : 正在获取 [美国国家漏洞数据库（NVD）] 威胁情报...
2022-03-18 22:57:43 [INFO] : 得到 [美国国家漏洞数据库（NVD）] 最新威胁情报 [0] 条
2022-03-18 22:57:43 [INFO] : --------------------------------------------
2022-03-18 22:57:43 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:57:43 [INFO] : 正在获取 [信息安全漏洞门户] 威胁情报...
2022-03-18 22:57:43 [INFO] : 得到 [信息安全漏洞门户] 最新威胁情报 [0] 条
2022-03-18 22:57:43 [INFO] : --------------------------------------------
2022-03-18 22:57:43 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:57:43 [INFO] : 正在获取 [绿盟] 威胁情报...
2022-03-18 22:57:52 [INFO] : 得到 [绿盟] 最新威胁情报 [0] 条
2022-03-18 22:57:52 [INFO] : --------------------------------------------
2022-03-18 22:57:52 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:57:52 [INFO] : 正在获取 [奇安信] 威胁情报...
2022-03-18 22:57:53 [INFO] : 得到 [奇安信] 最新威胁情报 [0] 条
2022-03-18 22:57:53 [INFO] : --------------------------------------------
2022-03-18 22:57:53 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:57:53 [INFO] : 正在获取 [红后] 威胁情报...
2022-03-18 22:57:53 [INFO] : 得到 [红后] 最新威胁情报 [0] 条
2022-03-18 22:57:53 [INFO] : --------------------------------------------
2022-03-18 22:57:53 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:57:53 [INFO] : 正在获取 [斗象] 威胁情报...
2022-03-18 22:57:56 [INFO] : 得到 [斗象] 最新威胁情报 [0] 条
2022-03-18 22:57:56 [INFO] : --------------------------------------------
2022-03-18 22:57:56 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:57:56 [INFO] : 正在获取 [Tenable (Nessus)] 威胁情报...
2022-03-18 22:57:57 [INFO] : 得到 [Tenable (Nessus)] 最新威胁情报 [0] 条
2022-03-18 22:57:57 [INFO] : --------------------------------------------
2022-03-18 22:57:57 [INFO] : ('1024593536@qq.com', 'ntcrbdovjjdbbfde')
2022-03-18 22:57:57 [INFO] : [邮件] 正在推送威胁情报...
2022-03-18 22:57:57 [INFO] : [邮件] 收件人清单： ['207176126@qq.com']
2022-03-18 22:57:57 [INFO] : [邮件] 推送威胁情报成功
2022-03-18 22:59:12 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:59:12 [INFO] : 正在获取 [数字观星POC++] 威胁情报...
2022-03-18 22:59:12 [INFO] : 得到 [数字观星POC++] 最新威胁情报 [0] 条
2022-03-18 22:59:12 [INFO] : --------------------------------------------
2022-03-18 22:59:12 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:59:12 [INFO] : 正在获取 [阿里云] 威胁情报...
2022-03-18 22:59:13 [INFO] : 得到 [阿里云] 最新威胁情报 [0] 条
2022-03-18 22:59:13 [INFO] : --------------------------------------------
2022-03-18 22:59:13 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:59:13 [INFO] : 正在获取 [国家信息安全漏洞共享平台（CNVD）] 威胁情报...
2022-03-18 22:59:35 [INFO] : 得到 [国家信息安全漏洞共享平台（CNVD）] 最新威胁情报 [0] 条
2022-03-18 22:59:35 [INFO] : --------------------------------------------
2022-03-18 22:59:35 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:59:35 [INFO] : 正在获取 [国家信息安全漏洞库（CNNVD）] 威胁情报...
2022-03-18 22:59:52 [INFO] : 得到 [国家信息安全漏洞库（CNNVD）] 最新威胁情报 [0] 条
2022-03-18 22:59:52 [INFO] : --------------------------------------------
2022-03-18 22:59:52 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:59:52 [INFO] : 正在获取 [360 网络安全响应中心] 威胁情报...
2022-03-18 22:59:53 [INFO] : 得到 [360 网络安全响应中心] 最新威胁情报 [0] 条
2022-03-18 22:59:53 [INFO] : --------------------------------------------
2022-03-18 22:59:53 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:59:53 [INFO] : 正在获取 [美国国家漏洞数据库（NVD）] 威胁情报...
2022-03-18 22:59:56 [INFO] : 得到 [美国国家漏洞数据库（NVD）] 最新威胁情报 [0] 条
2022-03-18 22:59:56 [INFO] : --------------------------------------------
2022-03-18 22:59:56 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:59:56 [INFO] : 正在获取 [信息安全漏洞门户] 威胁情报...
2022-03-18 22:59:57 [INFO] : 得到 [信息安全漏洞门户] 最新威胁情报 [0] 条
2022-03-18 22:59:57 [INFO] : --------------------------------------------
2022-03-18 22:59:57 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:59:57 [INFO] : 正在获取 [绿盟] 威胁情报...
2022-03-18 22:59:58 [INFO] : 得到 [绿盟] 最新威胁情报 [0] 条
2022-03-18 22:59:58 [INFO] : --------------------------------------------
2022-03-18 22:59:58 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:59:58 [INFO] : 正在获取 [奇安信] 威胁情报...
2022-03-18 22:59:58 [INFO] : 得到 [奇安信] 最新威胁情报 [0] 条
2022-03-18 22:59:58 [INFO] : --------------------------------------------
2022-03-18 22:59:58 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:59:58 [INFO] : 正在获取 [红后] 威胁情报...
2022-03-18 22:59:59 [INFO] : 得到 [红后] 最新威胁情报 [0] 条
2022-03-18 22:59:59 [INFO] : --------------------------------------------
2022-03-18 22:59:59 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 22:59:59 [INFO] : 正在获取 [斗象] 威胁情报...
2022-03-18 23:00:02 [INFO] : 得到 [斗象] 最新威胁情报 [0] 条
2022-03-18 23:00:02 [INFO] : --------------------------------------------
2022-03-18 23:00:02 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:00:02 [INFO] : 正在获取 [Tenable (Nessus)] 威胁情报...
2022-03-18 23:00:02 [INFO] : 得到 [Tenable (Nessus)] 最新威胁情报 [0] 条
2022-03-18 23:00:02 [INFO] : --------------------------------------------
2022-03-18 23:00:02 [INFO] : 正在提交变更...
2022-03-18 23:00:05 [ERROR] : 提交变更失败
Traceback (most recent call last):
  File "/root/project/threat-broadcast-1/src/utils/_git.py", line 26, in auto_commit
    repo.git.push()
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git push
  stderr: 'To git@github.com:hkmayfly/threat-broadcast-1.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@github.com:hkmayfly/threat-broadcast-1.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first merge the remote changes (e.g.,
hint: 'git pull') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.'
2022-03-18 23:00:05 [ERROR] : Traceback (most recent call last):
  File "/root/project/threat-broadcast-1/src/utils/_git.py", line 26, in auto_commit
    repo.git.push()
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git push
  stderr: 'To git@github.com:hkmayfly/threat-broadcast-1.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@github.com:hkmayfly/threat-broadcast-1.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first merge the remote changes (e.g.,
hint: 'git pull') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.'
Traceback (most recent call last):
  File "/root/project/threat-broadcast-1/src/utils/_git.py", line 26, in auto_commit
    repo.git.push()
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git push
  stderr: 'To git@github.com:hkmayfly/threat-broadcast-1.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'git@github.com:hkmayfly/threat-broadcast-1.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first merge the remote changes (e.g.,
hint: 'git pull') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.'
2022-03-18 23:02:27 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:02:27 [INFO] : 正在获取 [数字观星POC++] 威胁情报...
2022-03-18 23:02:28 [INFO] : 得到 [数字观星POC++] 最新威胁情报 [0] 条
2022-03-18 23:02:28 [INFO] : --------------------------------------------
2022-03-18 23:02:28 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:02:28 [INFO] : 正在获取 [阿里云] 威胁情报...
2022-03-18 23:02:28 [INFO] : 得到 [阿里云] 最新威胁情报 [0] 条
2022-03-18 23:02:28 [INFO] : --------------------------------------------
2022-03-18 23:02:28 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:02:28 [INFO] : 正在获取 [国家信息安全漏洞共享平台（CNVD）] 威胁情报...
2022-03-18 23:03:55 [INFO] : 得到 [国家信息安全漏洞共享平台（CNVD）] 最新威胁情报 [0] 条
2022-03-18 23:03:55 [INFO] : --------------------------------------------
2022-03-18 23:03:55 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:03:55 [INFO] : 正在获取 [国家信息安全漏洞库（CNNVD）] 威胁情报...
2022-03-18 23:04:14 [INFO] : 得到 [国家信息安全漏洞库（CNNVD）] 最新威胁情报 [0] 条
2022-03-18 23:04:14 [INFO] : --------------------------------------------
2022-03-18 23:04:14 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:04:14 [INFO] : 正在获取 [360 网络安全响应中心] 威胁情报...
2022-03-18 23:05:15 [ERROR] : 获取 [360 网络安全响应中心] 威胁情报异常
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/python3/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/python3/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/python3/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1091: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='cert.360.cn', port=443): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/project/threat-broadcast-1/src/crawler/_base_crawler.py", line 62, in cves
    new_cves = self.get_cves()
  File "/root/project/threat-broadcast-1/src/crawler/cert360.py", line 48, in get_cves
    response = requests.get(
  File "/usr/local/python3/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='cert.360.cn', port=443): Read timed out. (read timeout=60)
2022-03-18 23:05:15 [ERROR] : Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/python3/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/python3/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/python3/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1091: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='cert.360.cn', port=443): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/project/threat-broadcast-1/src/crawler/_base_crawler.py", line 62, in cves
    new_cves = self.get_cves()
  File "/root/project/threat-broadcast-1/src/crawler/cert360.py", line 48, in get_cves
    response = requests.get(
  File "/usr/local/python3/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='cert.360.cn', port=443): Read timed out. (read timeout=60)
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 381, in _make_request
    self._validate_conn(conn)
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 978, in _validate_conn
    conn.connect()
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connection.py", line 362, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 386, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/python3/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/python3/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/python3/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1091: The handshake operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/util/retry.py", line 410, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=conn.timeout)
  File "/usr/local/python3/lib/python3.8/site-packages/urllib3/connectionpool.py", line 335, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='cert.360.cn', port=443): Read timed out. (read timeout=60)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/project/threat-broadcast-1/src/crawler/_base_crawler.py", line 62, in cves
    new_cves = self.get_cves()
  File "/root/project/threat-broadcast-1/src/crawler/cert360.py", line 48, in get_cves
    response = requests.get(
  File "/usr/local/python3/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/requests/adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='cert.360.cn', port=443): Read timed out. (read timeout=60)
2022-03-18 23:05:15 [INFO] : 得到 [360 网络安全响应中心] 最新威胁情报 [0] 条
2022-03-18 23:05:15 [INFO] : --------------------------------------------
2022-03-18 23:05:15 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:05:15 [INFO] : 正在获取 [美国国家漏洞数据库（NVD）] 威胁情报...
2022-03-18 23:05:18 [INFO] : 得到 [美国国家漏洞数据库（NVD）] 最新威胁情报 [0] 条
2022-03-18 23:05:18 [INFO] : --------------------------------------------
2022-03-18 23:05:18 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:05:18 [INFO] : 正在获取 [信息安全漏洞门户] 威胁情报...
2022-03-18 23:05:19 [INFO] : 得到 [信息安全漏洞门户] 最新威胁情报 [0] 条
2022-03-18 23:05:19 [INFO] : --------------------------------------------
2022-03-18 23:05:19 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:05:19 [INFO] : 正在获取 [绿盟] 威胁情报...
2022-03-18 23:05:19 [INFO] : 得到 [绿盟] 最新威胁情报 [0] 条
2022-03-18 23:05:19 [INFO] : --------------------------------------------
2022-03-18 23:05:19 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:05:19 [INFO] : 正在获取 [奇安信] 威胁情报...
2022-03-18 23:05:20 [INFO] : 得到 [奇安信] 最新威胁情报 [0] 条
2022-03-18 23:05:20 [INFO] : --------------------------------------------
2022-03-18 23:05:20 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:05:20 [INFO] : 正在获取 [红后] 威胁情报...
2022-03-18 23:05:21 [INFO] : 得到 [红后] 最新威胁情报 [0] 条
2022-03-18 23:05:21 [INFO] : --------------------------------------------
2022-03-18 23:05:21 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:05:21 [INFO] : 正在获取 [斗象] 威胁情报...
2022-03-18 23:05:24 [INFO] : 得到 [斗象] 最新威胁情报 [0] 条
2022-03-18 23:05:24 [INFO] : --------------------------------------------
2022-03-18 23:05:24 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:05:24 [INFO] : 正在获取 [Tenable (Nessus)] 威胁情报...
2022-03-18 23:05:25 [INFO] : 得到 [Tenable (Nessus)] 最新威胁情报 [0] 条
2022-03-18 23:05:25 [INFO] : --------------------------------------------
2022-03-18 23:05:25 [INFO] : 正在提交变更...
2022-03-18 23:05:28 [ERROR] : 提交变更失败
Traceback (most recent call last):
  File "/root/project/threat-broadcast-1/src/utils/_git.py", line 26, in auto_commit
    repo.git.push()
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git push
  stderr: 'To git@github.com:hkmayfly/threat-broadcast-1.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:hkmayfly/threat-broadcast-1.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Merge the remote changes (e.g. 'git pull')
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.'
2022-03-18 23:05:28 [ERROR] : Traceback (most recent call last):
  File "/root/project/threat-broadcast-1/src/utils/_git.py", line 26, in auto_commit
    repo.git.push()
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git push
  stderr: 'To git@github.com:hkmayfly/threat-broadcast-1.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:hkmayfly/threat-broadcast-1.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Merge the remote changes (e.g. 'git pull')
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.'
Traceback (most recent call last):
  File "/root/project/threat-broadcast-1/src/utils/_git.py", line 26, in auto_commit
    repo.git.push()
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git push
  stderr: 'To git@github.com:hkmayfly/threat-broadcast-1.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:hkmayfly/threat-broadcast-1.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Merge the remote changes (e.g. 'git pull')
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.'
2022-03-18 23:11:35 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:11:35 [INFO] : 正在获取 [数字观星POC++] 威胁情报...
2022-03-18 23:11:35 [INFO] : 得到 [数字观星POC++] 最新威胁情报 [0] 条
2022-03-18 23:11:35 [INFO] : --------------------------------------------
2022-03-18 23:11:35 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:11:35 [INFO] : 正在获取 [阿里云] 威胁情报...
2022-03-18 23:11:36 [INFO] : 得到 [阿里云] 最新威胁情报 [0] 条
2022-03-18 23:11:36 [INFO] : --------------------------------------------
2022-03-18 23:11:36 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:11:36 [INFO] : 正在获取 [国家信息安全漏洞共享平台（CNVD）] 威胁情报...
2022-03-18 23:11:58 [INFO] : 得到 [国家信息安全漏洞共享平台（CNVD）] 最新威胁情报 [0] 条
2022-03-18 23:11:58 [INFO] : --------------------------------------------
2022-03-18 23:11:58 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:11:58 [INFO] : 正在获取 [国家信息安全漏洞库（CNNVD）] 威胁情报...
2022-03-18 23:12:14 [INFO] : 得到 [国家信息安全漏洞库（CNNVD）] 最新威胁情报 [0] 条
2022-03-18 23:12:14 [INFO] : --------------------------------------------
2022-03-18 23:12:14 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:12:14 [INFO] : 正在获取 [360 网络安全响应中心] 威胁情报...
2022-03-18 23:12:15 [INFO] : 得到 [360 网络安全响应中心] 最新威胁情报 [0] 条
2022-03-18 23:12:15 [INFO] : --------------------------------------------
2022-03-18 23:12:15 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:12:15 [INFO] : 正在获取 [美国国家漏洞数据库（NVD）] 威胁情报...
2022-03-18 23:12:17 [INFO] : 得到 [美国国家漏洞数据库（NVD）] 最新威胁情报 [0] 条
2022-03-18 23:12:17 [INFO] : --------------------------------------------
2022-03-18 23:12:17 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:12:17 [INFO] : 正在获取 [信息安全漏洞门户] 威胁情报...
2022-03-18 23:12:17 [INFO] : 得到 [信息安全漏洞门户] 最新威胁情报 [0] 条
2022-03-18 23:12:17 [INFO] : --------------------------------------------
2022-03-18 23:12:17 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:12:17 [INFO] : 正在获取 [绿盟] 威胁情报...
2022-03-18 23:12:17 [INFO] : 得到 [绿盟] 最新威胁情报 [0] 条
2022-03-18 23:12:17 [INFO] : --------------------------------------------
2022-03-18 23:12:17 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:12:17 [INFO] : 正在获取 [奇安信] 威胁情报...
2022-03-18 23:12:18 [INFO] : 得到 [奇安信] 最新威胁情报 [0] 条
2022-03-18 23:12:18 [INFO] : --------------------------------------------
2022-03-18 23:12:18 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:12:18 [INFO] : 正在获取 [红后] 威胁情报...
2022-03-18 23:12:18 [INFO] : 得到 [红后] 最新威胁情报 [0] 条
2022-03-18 23:12:18 [INFO] : --------------------------------------------
2022-03-18 23:12:18 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:12:18 [INFO] : 正在获取 [斗象] 威胁情报...
2022-03-18 23:12:24 [INFO] : 得到 [斗象] 最新威胁情报 [0] 条
2022-03-18 23:12:24 [INFO] : --------------------------------------------
2022-03-18 23:12:24 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:12:24 [INFO] : 正在获取 [Tenable (Nessus)] 威胁情报...
2022-03-18 23:12:24 [INFO] : 得到 [Tenable (Nessus)] 最新威胁情报 [0] 条
2022-03-18 23:12:24 [INFO] : --------------------------------------------
2022-03-18 23:12:24 [INFO] : 正在提交变更...
2022-03-18 23:12:27 [ERROR] : 提交变更失败
Traceback (most recent call last):
  File "/root/project/threat-broadcast-1/src/utils/_git.py", line 26, in auto_commit
    repo.git.push()
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git push
  stderr: 'To git@github.com:hkmayfly/threat-broadcast-1.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:hkmayfly/threat-broadcast-1.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Merge the remote changes (e.g. 'git pull')
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.'
2022-03-18 23:12:27 [ERROR] : Traceback (most recent call last):
  File "/root/project/threat-broadcast-1/src/utils/_git.py", line 26, in auto_commit
    repo.git.push()
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git push
  stderr: 'To git@github.com:hkmayfly/threat-broadcast-1.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:hkmayfly/threat-broadcast-1.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Merge the remote changes (e.g. 'git pull')
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.'
Traceback (most recent call last):
  File "/root/project/threat-broadcast-1/src/utils/_git.py", line 26, in auto_commit
    repo.git.push()
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 542, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 1005, in _call_process
    return self.execute(call, **exec_kwargs)
  File "/usr/local/python3/lib/python3.8/site-packages/git/cmd.py", line 822, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git push
  stderr: 'To git@github.com:hkmayfly/threat-broadcast-1.git
 ! [rejected]        master -> master (non-fast-forward)
error: failed to push some refs to 'git@github.com:hkmayfly/threat-broadcast-1.git'
hint: Updates were rejected because the tip of your current branch is behind
hint: its remote counterpart. Merge the remote changes (e.g. 'git pull')
hint: before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.'
2022-03-18 23:24:45 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:24:45 [INFO] : 正在获取 [数字观星POC++] 威胁情报...
2022-03-18 23:24:46 [INFO] : 得到 [数字观星POC++] 最新威胁情报 [0] 条
2022-03-18 23:24:46 [INFO] : --------------------------------------------
2022-03-18 23:24:46 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:24:46 [INFO] : 正在获取 [阿里云] 威胁情报...
2022-03-18 23:24:46 [INFO] : 得到 [阿里云] 最新威胁情报 [0] 条
2022-03-18 23:24:46 [INFO] : --------------------------------------------
2022-03-18 23:24:46 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:24:46 [INFO] : 正在获取 [国家信息安全漏洞共享平台（CNVD）] 威胁情报...
2022-03-18 23:25:08 [INFO] : 得到 [国家信息安全漏洞共享平台（CNVD）] 最新威胁情报 [0] 条
2022-03-18 23:25:08 [INFO] : --------------------------------------------
2022-03-18 23:25:08 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:25:08 [INFO] : 正在获取 [国家信息安全漏洞库（CNNVD）] 威胁情报...
2022-03-18 23:25:24 [INFO] : 得到 [国家信息安全漏洞库（CNNVD）] 最新威胁情报 [0] 条
2022-03-18 23:25:24 [INFO] : --------------------------------------------
2022-03-18 23:25:24 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:25:24 [INFO] : 正在获取 [360 网络安全响应中心] 威胁情报...
2022-03-18 23:25:24 [INFO] : 得到 [360 网络安全响应中心] 最新威胁情报 [0] 条
2022-03-18 23:25:24 [INFO] : --------------------------------------------
2022-03-18 23:25:24 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:25:24 [INFO] : 正在获取 [美国国家漏洞数据库（NVD）] 威胁情报...
2022-03-18 23:25:26 [INFO] : 得到 [美国国家漏洞数据库（NVD）] 最新威胁情报 [0] 条
2022-03-18 23:25:26 [INFO] : --------------------------------------------
2022-03-18 23:25:26 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:25:26 [INFO] : 正在获取 [信息安全漏洞门户] 威胁情报...
2022-03-18 23:25:27 [INFO] : 得到 [信息安全漏洞门户] 最新威胁情报 [0] 条
2022-03-18 23:25:27 [INFO] : --------------------------------------------
2022-03-18 23:25:27 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:25:27 [INFO] : 正在获取 [绿盟] 威胁情报...
2022-03-18 23:25:27 [INFO] : 得到 [绿盟] 最新威胁情报 [0] 条
2022-03-18 23:25:27 [INFO] : --------------------------------------------
2022-03-18 23:25:27 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:25:27 [INFO] : 正在获取 [奇安信] 威胁情报...
2022-03-18 23:25:28 [INFO] : 得到 [奇安信] 最新威胁情报 [0] 条
2022-03-18 23:25:28 [INFO] : --------------------------------------------
2022-03-18 23:25:28 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:25:28 [INFO] : 正在获取 [红后] 威胁情报...
2022-03-18 23:25:28 [INFO] : 得到 [红后] 最新威胁情报 [0] 条
2022-03-18 23:25:28 [INFO] : --------------------------------------------
2022-03-18 23:25:28 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:25:28 [INFO] : 正在获取 [斗象] 威胁情报...
2022-03-18 23:25:31 [INFO] : 得到 [斗象] 最新威胁情报 [0] 条
2022-03-18 23:25:31 [INFO] : --------------------------------------------
2022-03-18 23:25:31 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 23:25:31 [INFO] : 正在获取 [Tenable (Nessus)] 威胁情报...
2022-03-18 23:25:31 [INFO] : 得到 [Tenable (Nessus)] 最新威胁情报 [0] 条
2022-03-18 23:25:31 [INFO] : --------------------------------------------
2022-03-18 23:25:31 [INFO] : 正在提交变更...
2022-03-18 15:38:33 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 15:38:33 [INFO] : 正在获取 [数字观星POC++] 威胁情报...
2022-03-18 15:38:34 [INFO] : 得到 [数字观星POC++] 最新威胁情报 [0] 条
2022-03-18 15:38:34 [INFO] : --------------------------------------------
2022-03-18 15:38:34 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 15:38:34 [INFO] : 正在获取 [阿里云] 威胁情报...
2022-03-18 15:38:36 [INFO] : 得到 [阿里云] 最新威胁情报 [0] 条
2022-03-18 15:38:36 [INFO] : --------------------------------------------
2022-03-18 15:38:36 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 15:38:36 [INFO] : 正在获取 [国家信息安全漏洞共享平台（CNVD）] 威胁情报...
2022-03-18 15:39:00 [INFO] : 得到 [国家信息安全漏洞共享平台（CNVD）] 最新威胁情报 [0] 条
2022-03-18 15:39:00 [INFO] : --------------------------------------------
2022-03-18 15:39:00 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 15:39:00 [INFO] : 正在获取 [国家信息安全漏洞库（CNNVD）] 威胁情报...
2022-03-18 15:39:23 [INFO] : 得到 [国家信息安全漏洞库（CNNVD）] 最新威胁情报 [0] 条
2022-03-18 15:39:23 [INFO] : --------------------------------------------
2022-03-18 15:39:23 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 15:39:23 [INFO] : 正在获取 [360 网络安全响应中心] 威胁情报...
2022-03-18 15:39:25 [INFO] : 得到 [360 网络安全响应中心] 最新威胁情报 [0] 条
2022-03-18 15:39:25 [INFO] : --------------------------------------------
2022-03-18 15:39:25 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 15:39:25 [INFO] : 正在获取 [美国国家漏洞数据库（NVD）] 威胁情报...
2022-03-18 15:39:25 [INFO] : 得到 [美国国家漏洞数据库（NVD）] 最新威胁情报 [0] 条
2022-03-18 15:39:25 [INFO] : --------------------------------------------
2022-03-18 15:39:25 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 15:39:25 [INFO] : 正在获取 [信息安全漏洞门户] 威胁情报...
2022-03-18 15:39:27 [INFO] : 得到 [信息安全漏洞门户] 最新威胁情报 [0] 条
2022-03-18 15:39:27 [INFO] : --------------------------------------------
2022-03-18 15:39:27 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 15:39:27 [INFO] : 正在获取 [绿盟] 威胁情报...
2022-03-18 15:39:28 [INFO] : 得到 [绿盟] 最新威胁情报 [0] 条
2022-03-18 15:39:28 [INFO] : --------------------------------------------
2022-03-18 15:39:28 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 15:39:28 [INFO] : 正在获取 [奇安信] 威胁情报...
2022-03-18 15:39:35 [INFO] : 得到 [奇安信] 最新威胁情报 [0] 条
2022-03-18 15:39:35 [INFO] : --------------------------------------------
2022-03-18 15:39:35 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 15:39:35 [INFO] : 正在获取 [红后] 威胁情报...
2022-03-18 15:39:36 [INFO] : 得到 [红后] 最新威胁情报 [0] 条
2022-03-18 15:39:36 [INFO] : --------------------------------------------
2022-03-18 15:39:36 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 15:39:36 [INFO] : 正在获取 [斗象] 威胁情报...
2022-03-18 15:39:43 [INFO] : 得到 [斗象] 最新威胁情报 [0] 条
2022-03-18 15:39:43 [INFO] : --------------------------------------------
2022-03-18 15:39:43 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 15:39:43 [INFO] : 正在获取 [Tenable (Nessus)] 威胁情报...
2022-03-18 15:39:43 [INFO] : 得到 [Tenable (Nessus)] 最新威胁情报 [2] 条
2022-03-18 15:39:43 [INFO] : --------------------------------------------
2022-03-18 15:39:43 [INFO] : 
==============================================
[ TITLE ] Automotive Grade Linux Kooky Koi 11.0.0, 11.0.1, 11.0.2, 11.0.3, 11.0.4, and 11.0.5 is affected by Incorrect Access Control in usr/bin/afb-daemon. To exploit the vulnerability, an attacker should send a well-crafted HTTP (or WebSocket) request to the socket listened by the afb-daemon process. No credentials nor user interactions are required.
[ TIME  ] 2022-03-18 12:15:00
[ CVE   ] CVE-2022-24595
[ SRC   ] Tenable (Nessus)
[ URL   ] https://www.tenable.com/cve/CVE-2022-24595
2022-03-18 15:39:43 [INFO] : 
==============================================
[ TITLE ] Memory leak in icmp6 implementation in Linux Kernel 5.13+ allows a remote attacker to DoS a host by making it go out-of-memory via icmp6 packets of type 130 or 131. We recommend upgrading past commit 2d3916f3189172d5c69d33065c3c21119fe539fc.
[ TIME  ] 2022-03-18 12:15:00
[ CVE   ] CVE-2022-0742
[ SRC   ] Tenable (Nessus)
[ URL   ] https://www.tenable.com/cve/CVE-2022-0742
2022-03-18 15:39:43 [INFO] : [邮件] 正在推送威胁情报...
2022-03-18 15:39:43 [INFO] : [邮件] 收件人清单： ['207176126@qq.com']
2022-03-18 15:39:44 [ERROR] : [邮件] 推送威胁情报失败
Traceback (most recent call last):
  File "/home/runner/work/threat-broadcast-1/threat-broadcast-1/src/notice/mail.py", line 46, in to_mail
    smtpObj.login(sender, password)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/smtplib.py", line 737, in login
    (code, resp) = self.auth(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/smtplib.py", line 650, in auth
    authobject(challenge).encode('ascii'), eol='')
AttributeError: 'NoneType' object has no attribute 'encode'
2022-03-18 15:39:44 [ERROR] : Traceback (most recent call last):
  File "/home/runner/work/threat-broadcast-1/threat-broadcast-1/src/notice/mail.py", line 46, in to_mail
    smtpObj.login(sender, password)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/smtplib.py", line 737, in login
    (code, resp) = self.auth(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/smtplib.py", line 650, in auth
    authobject(challenge).encode('ascii'), eol='')
AttributeError: 'NoneType' object has no attribute 'encode'
Traceback (most recent call last):
  File "/home/runner/work/threat-broadcast-1/threat-broadcast-1/src/notice/mail.py", line 46, in to_mail
    smtpObj.login(sender, password)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/smtplib.py", line 737, in login
    (code, resp) = self.auth(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/smtplib.py", line 650, in auth
    authobject(challenge).encode('ascii'), eol='')
AttributeError: 'NoneType' object has no attribute 'encode'
>>>>>>> 3064b1f879ae4b11fb41e39d5d326ebafee0a9c8
2022-03-19 00:31:34 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:31:34 [INFO] : 正在获取 [数字观星POC++] 威胁情报...
2022-03-19 00:31:35 [INFO] : 得到 [数字观星POC++] 最新威胁情报 [0] 条
2022-03-19 00:31:35 [INFO] : --------------------------------------------
2022-03-19 00:31:35 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:31:35 [INFO] : 正在获取 [阿里云] 威胁情报...
2022-03-19 00:31:35 [INFO] : 得到 [阿里云] 最新威胁情报 [0] 条
2022-03-19 00:31:35 [INFO] : --------------------------------------------
2022-03-19 00:31:35 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:31:35 [INFO] : 正在获取 [国家信息安全漏洞共享平台（CNVD）] 威胁情报...
2022-03-19 00:31:57 [INFO] : 得到 [国家信息安全漏洞共享平台（CNVD）] 最新威胁情报 [0] 条
2022-03-19 00:31:57 [INFO] : --------------------------------------------
2022-03-19 00:31:57 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:31:57 [INFO] : 正在获取 [国家信息安全漏洞库（CNNVD）] 威胁情报...
2022-03-19 00:32:12 [INFO] : 得到 [国家信息安全漏洞库（CNNVD）] 最新威胁情报 [0] 条
2022-03-19 00:32:12 [INFO] : --------------------------------------------
2022-03-19 00:32:12 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:32:12 [INFO] : 正在获取 [360 网络安全响应中心] 威胁情报...
2022-03-19 00:32:12 [INFO] : 得到 [360 网络安全响应中心] 最新威胁情报 [0] 条
2022-03-19 00:32:12 [INFO] : --------------------------------------------
2022-03-19 00:32:12 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:32:12 [INFO] : 正在获取 [美国国家漏洞数据库（NVD）] 威胁情报...
2022-03-19 00:32:14 [INFO] : 得到 [美国国家漏洞数据库（NVD）] 最新威胁情报 [0] 条
2022-03-19 00:32:14 [INFO] : --------------------------------------------
2022-03-19 00:32:14 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:32:14 [INFO] : 正在获取 [信息安全漏洞门户] 威胁情报...
2022-03-19 00:32:15 [INFO] : 得到 [信息安全漏洞门户] 最新威胁情报 [0] 条
2022-03-19 00:32:15 [INFO] : --------------------------------------------
2022-03-19 00:32:15 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:32:15 [INFO] : 正在获取 [绿盟] 威胁情报...
2022-03-19 00:32:15 [INFO] : 得到 [绿盟] 最新威胁情报 [0] 条
2022-03-19 00:32:15 [INFO] : --------------------------------------------
2022-03-19 00:32:15 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:32:15 [INFO] : 正在获取 [奇安信] 威胁情报...
2022-03-19 00:32:17 [INFO] : 得到 [奇安信] 最新威胁情报 [0] 条
2022-03-19 00:32:17 [INFO] : --------------------------------------------
2022-03-19 00:32:17 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:32:17 [INFO] : 正在获取 [红后] 威胁情报...
2022-03-19 00:32:17 [INFO] : 得到 [红后] 最新威胁情报 [0] 条
2022-03-19 00:32:17 [INFO] : --------------------------------------------
2022-03-19 00:32:17 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:32:17 [INFO] : 正在获取 [斗象] 威胁情报...
2022-03-19 00:32:20 [INFO] : 得到 [斗象] 最新威胁情报 [0] 条
2022-03-19 00:32:20 [INFO] : --------------------------------------------
2022-03-19 00:32:20 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:32:20 [INFO] : 正在获取 [Tenable (Nessus)] 威胁情报...
2022-03-19 00:32:20 [INFO] : 得到 [Tenable (Nessus)] 最新威胁情报 [0] 条
2022-03-19 00:32:20 [INFO] : --------------------------------------------
2022-03-19 00:32:20 [INFO] : 正在提交变更...
2022-03-19 00:32:26 [INFO] : 提交变更成功
2022-03-19 00:36:32 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:36:32 [INFO] : 正在获取 [数字观星POC++] 威胁情报...
2022-03-19 00:36:33 [INFO] : 得到 [数字观星POC++] 最新威胁情报 [0] 条
2022-03-19 00:36:33 [INFO] : --------------------------------------------
2022-03-19 00:36:33 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:36:33 [INFO] : 正在获取 [阿里云] 威胁情报...
2022-03-19 00:36:33 [INFO] : 得到 [阿里云] 最新威胁情报 [0] 条
2022-03-19 00:36:33 [INFO] : --------------------------------------------
2022-03-19 00:36:33 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:36:33 [INFO] : 正在获取 [国家信息安全漏洞共享平台（CNVD）] 威胁情报...
2022-03-19 00:36:54 [INFO] : 得到 [国家信息安全漏洞共享平台（CNVD）] 最新威胁情报 [0] 条
2022-03-19 00:36:54 [INFO] : --------------------------------------------
2022-03-19 00:36:54 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:36:54 [INFO] : 正在获取 [国家信息安全漏洞库（CNNVD）] 威胁情报...
2022-03-19 00:37:08 [INFO] : 得到 [国家信息安全漏洞库（CNNVD）] 最新威胁情报 [0] 条
2022-03-19 00:37:08 [INFO] : --------------------------------------------
2022-03-19 00:37:08 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:37:08 [INFO] : 正在获取 [360 网络安全响应中心] 威胁情报...
2022-03-19 00:37:10 [INFO] : 得到 [360 网络安全响应中心] 最新威胁情报 [0] 条
2022-03-19 00:37:10 [INFO] : --------------------------------------------
2022-03-19 00:37:10 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:37:10 [INFO] : 正在获取 [美国国家漏洞数据库（NVD）] 威胁情报...
2022-03-19 00:37:12 [INFO] : 得到 [美国国家漏洞数据库（NVD）] 最新威胁情报 [0] 条
2022-03-19 00:37:12 [INFO] : --------------------------------------------
2022-03-19 00:37:12 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:37:12 [INFO] : 正在获取 [信息安全漏洞门户] 威胁情报...
2022-03-19 00:37:12 [INFO] : 得到 [信息安全漏洞门户] 最新威胁情报 [0] 条
2022-03-19 00:37:12 [INFO] : --------------------------------------------
2022-03-19 00:37:12 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:37:12 [INFO] : 正在获取 [绿盟] 威胁情报...
2022-03-19 00:37:12 [INFO] : 得到 [绿盟] 最新威胁情报 [0] 条
2022-03-19 00:37:12 [INFO] : --------------------------------------------
2022-03-19 00:37:12 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:37:12 [INFO] : 正在获取 [奇安信] 威胁情报...
2022-03-19 00:37:13 [INFO] : 得到 [奇安信] 最新威胁情报 [0] 条
2022-03-19 00:37:13 [INFO] : --------------------------------------------
2022-03-19 00:37:13 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:37:13 [INFO] : 正在获取 [红后] 威胁情报...
2022-03-19 00:37:13 [INFO] : 得到 [红后] 最新威胁情报 [0] 条
2022-03-19 00:37:13 [INFO] : --------------------------------------------
2022-03-19 00:37:13 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:37:13 [INFO] : 正在获取 [斗象] 威胁情报...
2022-03-19 00:37:16 [INFO] : 得到 [斗象] 最新威胁情报 [0] 条
2022-03-19 00:37:16 [INFO] : --------------------------------------------
2022-03-19 00:37:16 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:37:16 [INFO] : 正在获取 [Tenable (Nessus)] 威胁情报...
2022-03-19 00:37:16 [INFO] : 得到 [Tenable (Nessus)] 最新威胁情报 [0] 条
2022-03-19 00:37:16 [INFO] : --------------------------------------------
2022-03-19 00:37:16 [INFO] : 正在提交变更...
2022-03-19 00:37:19 [INFO] : 提交变更成功
2022-03-19 00:41:20 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:41:20 [INFO] : 正在获取 [数字观星POC++] 威胁情报...
2022-03-19 00:41:21 [INFO] : 得到 [数字观星POC++] 最新威胁情报 [0] 条
2022-03-19 00:41:21 [INFO] : --------------------------------------------
2022-03-19 00:41:21 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:41:21 [INFO] : 正在获取 [阿里云] 威胁情报...
2022-03-19 00:41:21 [INFO] : 得到 [阿里云] 最新威胁情报 [0] 条
2022-03-19 00:41:21 [INFO] : --------------------------------------------
2022-03-19 00:41:21 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:41:21 [INFO] : 正在获取 [国家信息安全漏洞共享平台（CNVD）] 威胁情报...
2022-03-19 00:41:44 [INFO] : 得到 [国家信息安全漏洞共享平台（CNVD）] 最新威胁情报 [0] 条
2022-03-19 00:41:44 [INFO] : --------------------------------------------
2022-03-19 00:41:44 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:41:44 [INFO] : 正在获取 [国家信息安全漏洞库（CNNVD）] 威胁情报...
2022-03-19 00:41:58 [INFO] : 得到 [国家信息安全漏洞库（CNNVD）] 最新威胁情报 [0] 条
2022-03-19 00:41:58 [INFO] : --------------------------------------------
2022-03-19 00:41:58 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:41:58 [INFO] : 正在获取 [360 网络安全响应中心] 威胁情报...
2022-03-19 00:41:58 [INFO] : 得到 [360 网络安全响应中心] 最新威胁情报 [0] 条
2022-03-19 00:41:58 [INFO] : --------------------------------------------
2022-03-19 00:41:58 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:41:58 [INFO] : 正在获取 [美国国家漏洞数据库（NVD）] 威胁情报...
2022-03-19 00:42:00 [INFO] : 得到 [美国国家漏洞数据库（NVD）] 最新威胁情报 [0] 条
2022-03-19 00:42:00 [INFO] : --------------------------------------------
2022-03-19 00:42:00 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:42:00 [INFO] : 正在获取 [信息安全漏洞门户] 威胁情报...
2022-03-19 00:42:01 [INFO] : 得到 [信息安全漏洞门户] 最新威胁情报 [1] 条
2022-03-19 00:42:01 [INFO] : --------------------------------------------
2022-03-19 00:42:01 [INFO] : 
==============================================
[ TITLE ] Simple Mobile Comparison Website 1.0 Cross...
                    
[ TIME  ] 2022-03-18 00:42:01
[ CVE   ] VHN-417860
[ SRC   ] 信息安全漏洞门户
[ URL   ] http://cve.scap.org.cn/vuln/VHN-417860
2022-03-19 00:42:01 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:42:01 [INFO] : 正在获取 [绿盟] 威胁情报...
2022-03-19 00:42:01 [INFO] : 得到 [绿盟] 最新威胁情报 [0] 条
2022-03-19 00:42:01 [INFO] : --------------------------------------------
2022-03-19 00:42:01 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:42:01 [INFO] : 正在获取 [奇安信] 威胁情报...
2022-03-19 00:42:02 [INFO] : 得到 [奇安信] 最新威胁情报 [0] 条
2022-03-19 00:42:02 [INFO] : --------------------------------------------
2022-03-19 00:42:02 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:42:02 [INFO] : 正在获取 [红后] 威胁情报...
2022-03-19 00:42:02 [INFO] : 得到 [红后] 最新威胁情报 [0] 条
2022-03-19 00:42:02 [INFO] : --------------------------------------------
2022-03-19 00:42:02 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:42:02 [INFO] : 正在获取 [斗象] 威胁情报...
2022-03-19 00:42:05 [INFO] : 得到 [斗象] 最新威胁情报 [0] 条
2022-03-19 00:42:05 [INFO] : --------------------------------------------
2022-03-19 00:42:05 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-19 00:42:05 [INFO] : 正在获取 [Tenable (Nessus)] 威胁情报...
2022-03-19 00:42:05 [INFO] : 得到 [Tenable (Nessus)] 最新威胁情报 [0] 条
2022-03-19 00:42:05 [INFO] : --------------------------------------------
2022-03-19 00:42:05 [INFO] : [邮件] 正在推送威胁情报...
2022-03-19 00:42:05 [INFO] : [邮件] 收件人清单： ['207176126@qq.com']
2022-03-19 00:42:06 [INFO] : [邮件] 推送威胁情报成功
2022-03-19 00:42:06 [INFO] : 正在提交变更...
2022-03-18 16:52:16 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 16:52:16 [INFO] : 正在获取 [数字观星POC++] 威胁情报...
2022-03-18 16:52:17 [INFO] : 得到 [数字观星POC++] 最新威胁情报 [0] 条
2022-03-18 16:52:17 [INFO] : --------------------------------------------
2022-03-18 16:52:17 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 16:52:17 [INFO] : 正在获取 [阿里云] 威胁情报...
2022-03-18 16:52:19 [INFO] : 得到 [阿里云] 最新威胁情报 [0] 条
2022-03-18 16:52:19 [INFO] : --------------------------------------------
2022-03-18 16:52:19 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 16:52:19 [INFO] : 正在获取 [国家信息安全漏洞共享平台（CNVD）] 威胁情报...
2022-03-18 16:52:44 [INFO] : 得到 [国家信息安全漏洞共享平台（CNVD）] 最新威胁情报 [0] 条
2022-03-18 16:52:44 [INFO] : --------------------------------------------
2022-03-18 16:52:44 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 16:52:44 [INFO] : 正在获取 [国家信息安全漏洞库（CNNVD）] 威胁情报...
2022-03-18 16:53:07 [INFO] : 得到 [国家信息安全漏洞库（CNNVD）] 最新威胁情报 [0] 条
2022-03-18 16:53:07 [INFO] : --------------------------------------------
2022-03-18 16:53:07 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 16:53:07 [INFO] : 正在获取 [360 网络安全响应中心] 威胁情报...
2022-03-18 16:53:08 [INFO] : 得到 [360 网络安全响应中心] 最新威胁情报 [0] 条
2022-03-18 16:53:08 [INFO] : --------------------------------------------
2022-03-18 16:53:08 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 16:53:08 [INFO] : 正在获取 [美国国家漏洞数据库（NVD）] 威胁情报...
2022-03-18 16:53:08 [INFO] : 得到 [美国国家漏洞数据库（NVD）] 最新威胁情报 [0] 条
2022-03-18 16:53:08 [INFO] : --------------------------------------------
2022-03-18 16:53:08 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 16:53:08 [INFO] : 正在获取 [信息安全漏洞门户] 威胁情报...
2022-03-18 16:53:09 [INFO] : 得到 [信息安全漏洞门户] 最新威胁情报 [0] 条
2022-03-18 16:53:09 [INFO] : --------------------------------------------
2022-03-18 16:53:09 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 16:53:09 [INFO] : 正在获取 [绿盟] 威胁情报...
2022-03-18 16:53:10 [INFO] : 得到 [绿盟] 最新威胁情报 [0] 条
2022-03-18 16:53:10 [INFO] : --------------------------------------------
2022-03-18 16:53:10 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 16:53:10 [INFO] : 正在获取 [奇安信] 威胁情报...
2022-03-18 16:53:16 [INFO] : 得到 [奇安信] 最新威胁情报 [0] 条
2022-03-18 16:53:16 [INFO] : --------------------------------------------
2022-03-18 16:53:16 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 16:53:16 [INFO] : 正在获取 [红后] 威胁情报...
2022-03-18 16:53:17 [INFO] : 得到 [红后] 最新威胁情报 [0] 条
2022-03-18 16:53:17 [INFO] : --------------------------------------------
2022-03-18 16:53:17 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 16:53:17 [INFO] : 正在获取 [斗象] 威胁情报...
2022-03-18 16:53:23 [INFO] : 得到 [斗象] 最新威胁情报 [0] 条
2022-03-18 16:53:23 [INFO] : --------------------------------------------
2022-03-18 16:53:23 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 16:53:23 [INFO] : 正在获取 [Tenable (Nessus)] 威胁情报...
2022-03-18 16:53:23 [INFO] : 得到 [Tenable (Nessus)] 最新威胁情报 [0] 条
2022-03-18 16:53:23 [INFO] : --------------------------------------------
2022-03-18 17:36:35 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 17:36:35 [INFO] : 正在获取 [数字观星POC++] 威胁情报...
2022-03-18 17:36:36 [INFO] : 得到 [数字观星POC++] 最新威胁情报 [0] 条
2022-03-18 17:36:36 [INFO] : --------------------------------------------
2022-03-18 17:36:36 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 17:36:36 [INFO] : 正在获取 [阿里云] 威胁情报...
2022-03-18 17:36:37 [INFO] : 得到 [阿里云] 最新威胁情报 [0] 条
2022-03-18 17:36:37 [INFO] : --------------------------------------------
2022-03-18 17:36:37 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 17:36:37 [INFO] : 正在获取 [国家信息安全漏洞共享平台（CNVD）] 威胁情报...
2022-03-18 17:37:00 [INFO] : 得到 [国家信息安全漏洞共享平台（CNVD）] 最新威胁情报 [0] 条
2022-03-18 17:37:00 [INFO] : --------------------------------------------
2022-03-18 17:37:00 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 17:37:00 [INFO] : 正在获取 [国家信息安全漏洞库（CNNVD）] 威胁情报...
2022-03-18 17:37:22 [INFO] : 得到 [国家信息安全漏洞库（CNNVD）] 最新威胁情报 [0] 条
2022-03-18 17:37:22 [INFO] : --------------------------------------------
2022-03-18 17:37:22 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 17:37:22 [INFO] : 正在获取 [360 网络安全响应中心] 威胁情报...
2022-03-18 17:37:23 [INFO] : 得到 [360 网络安全响应中心] 最新威胁情报 [0] 条
2022-03-18 17:37:23 [INFO] : --------------------------------------------
2022-03-18 17:37:23 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 17:37:23 [INFO] : 正在获取 [美国国家漏洞数据库（NVD）] 威胁情报...
2022-03-18 17:37:24 [INFO] : 得到 [美国国家漏洞数据库（NVD）] 最新威胁情报 [0] 条
2022-03-18 17:37:24 [INFO] : --------------------------------------------
2022-03-18 17:37:24 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 17:37:24 [INFO] : 正在获取 [信息安全漏洞门户] 威胁情报...
2022-03-18 17:37:25 [INFO] : 得到 [信息安全漏洞门户] 最新威胁情报 [0] 条
2022-03-18 17:37:25 [INFO] : --------------------------------------------
2022-03-18 17:37:25 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 17:37:25 [INFO] : 正在获取 [绿盟] 威胁情报...
2022-03-18 17:37:26 [INFO] : 得到 [绿盟] 最新威胁情报 [0] 条
2022-03-18 17:37:26 [INFO] : --------------------------------------------
2022-03-18 17:37:26 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 17:37:26 [INFO] : 正在获取 [奇安信] 威胁情报...
2022-03-18 17:37:32 [INFO] : 得到 [奇安信] 最新威胁情报 [0] 条
2022-03-18 17:37:32 [INFO] : --------------------------------------------
2022-03-18 17:37:32 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 17:37:32 [INFO] : 正在获取 [红后] 威胁情报...
2022-03-18 17:37:33 [INFO] : 得到 [红后] 最新威胁情报 [0] 条
2022-03-18 17:37:33 [INFO] : --------------------------------------------
2022-03-18 17:37:33 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 17:37:33 [INFO] : 正在获取 [斗象] 威胁情报...
2022-03-18 17:37:40 [INFO] : 得到 [斗象] 最新威胁情报 [0] 条
2022-03-18 17:37:40 [INFO] : --------------------------------------------
2022-03-18 17:37:40 [INFO] : ++++++++++++++++++++++++++++++++++++++++++++
2022-03-18 17:37:40 [INFO] : 正在获取 [Tenable (Nessus)] 威胁情报...
2022-03-18 17:37:40 [INFO] : 得到 [Tenable (Nessus)] 最新威胁情报 [3] 条
2022-03-18 17:37:40 [INFO] : --------------------------------------------
2022-03-18 17:37:40 [INFO] : 
==============================================
[ TITLE ] Forge (also called `node-forge`) is a native implementation of Transport Layer Security in JavaScript. Prior to version 1.3.0, RSA PKCS#1 v1.5 signature verification code does not properly check `DigestInfo` for a proper ASN.1 structure. This can lead to successful verification with signatures that contain invalid structures but a valid digest. The issue has been addressed in `node-forge` version 1.3.0. There are currently no known workarounds.
[ TIME  ] 2022-03-18 14:15:00
[ CVE   ] CVE-2022-24773
[ SRC   ] Tenable (Nessus)
[ URL   ] https://www.tenable.com/cve/CVE-2022-24773
2022-03-18 17:37:40 [INFO] : 
==============================================
[ TITLE ] Forge (also called `node-forge`) is a native implementation of Transport Layer Security in JavaScript. Prior to version 1.3.0, RSA PKCS#1 v1.5 signature verification code does not check for tailing garbage bytes after decoding a `DigestInfo` ASN.1 structure. This can allow padding bytes to be removed and garbage data added to forge a signature when a low public exponent is being used. The issue has been addressed in `node-forge` version 1.3.0. There are currently no known workarounds.
[ TIME  ] 2022-03-18 14:15:00
[ CVE   ] CVE-2022-24772
[ SRC   ] Tenable (Nessus)
[ URL   ] https://www.tenable.com/cve/CVE-2022-24772
2022-03-18 17:37:40 [INFO] : 
==============================================
[ TITLE ] Forge (also called `node-forge`) is a native implementation of Transport Layer Security in JavaScript. Prior to version 1.3.0, RSA PKCS#1 v1.5 signature verification code is lenient in checking the digest algorithm structure. This can allow a crafted structure that steals padding bytes and uses unchecked portion of the PKCS#1 encoded message to forge a signature when a low public exponent is being used. The issue has been addressed in `node-forge` version 1.3.0. There are currently no known workarounds.
[ TIME  ] 2022-03-18 14:15:00
[ CVE   ] CVE-2022-24771
[ SRC   ] Tenable (Nessus)
[ URL   ] https://www.tenable.com/cve/CVE-2022-24771
2022-03-18 17:37:40 [INFO] : [邮件] 正在推送威胁情报...
2022-03-18 17:37:40 [INFO] : [邮件] 收件人清单： ['207176126@qq.com']
2022-03-18 17:37:41 [ERROR] : [邮件] 推送威胁情报失败
Traceback (most recent call last):
  File "/home/runner/work/threat-broadcast-1/threat-broadcast-1/src/notice/mail.py", line 46, in to_mail
    smtpObj.login(sender, password)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/smtplib.py", line 737, in login
    (code, resp) = self.auth(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/smtplib.py", line 650, in auth
    authobject(challenge).encode('ascii'), eol='')
AttributeError: 'NoneType' object has no attribute 'encode'
2022-03-18 17:37:41 [ERROR] : Traceback (most recent call last):
  File "/home/runner/work/threat-broadcast-1/threat-broadcast-1/src/notice/mail.py", line 46, in to_mail
    smtpObj.login(sender, password)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/smtplib.py", line 737, in login
    (code, resp) = self.auth(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/smtplib.py", line 650, in auth
    authobject(challenge).encode('ascii'), eol='')
AttributeError: 'NoneType' object has no attribute 'encode'
Traceback (most recent call last):
  File "/home/runner/work/threat-broadcast-1/threat-broadcast-1/src/notice/mail.py", line 46, in to_mail
    smtpObj.login(sender, password)
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/smtplib.py", line 737, in login
    (code, resp) = self.auth(
  File "/opt/hostedtoolcache/Python/3.8.12/x64/lib/python3.8/smtplib.py", line 650, in auth
    authobject(challenge).encode('ascii'), eol='')
AttributeError: 'NoneType' object has no attribute 'encode'
